In [1]:
import torch
import numpy as np

In [8]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))
#     print("Добавим 10 :\n%s\n" % (tensor + 10))
#     print("Среднее по строчке :\n%s\n" % (tensor.mean(axis=-1)))
#     print("Среднее по столбцу :\n%s\n" % (tensor.mean(axis=0)))

In [9]:
# 1. Создайте случайный FloatTensor размера 3x4x5
random_float_tensor = torch.randn(3, 4, 5)
print_tens_info(random_float_tensor)

X :
tensor([[[-2.0533,  0.6928, -1.1283,  0.0726,  2.9805],
         [ 0.7438,  0.6412, -0.1275,  0.4197,  0.4124],
         [ 0.3022, -0.8782, -1.1405,  0.6778,  0.0910],
         [ 0.8221,  0.5826, -1.1443,  0.1133, -1.9675]],

        [[-0.0872,  0.2376,  0.2568, -0.0889,  0.3757],
         [ 1.1661, -1.2175, -0.5541, -1.0031,  0.6302],
         [-0.4699,  0.5458,  0.6909,  0.0645,  0.1643],
         [-0.0718,  0.8474, -1.4140,  1.7196, -0.4215]],

        [[-1.2677,  0.5189,  1.0236, -0.6413, -0.9892],
         [-1.3942, -1.4767,  1.7769,  0.7540, -0.5320],
         [-0.0408,  1.1714, -0.0429,  0.8475, -0.6490],
         [ 0.2885, -1.2409, -0.9790,  0.1976,  0.8879]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.FloatTensor



In [10]:
# 2.1 Выведите его форму (shape)
random_float_tensor.shape

torch.Size([3, 4, 5])

In [11]:
# 2.2 Выведите его форму (size)
random_float_tensor.size()

torch.Size([3, 4, 5])

In [12]:
# 3. Приведите его к форме 6x10
reshaped_float_tensor = random_float_tensor.view(6, 10)
print_tens_info(reshaped_float_tensor)

X :
tensor([[-2.0533,  0.6928, -1.1283,  0.0726,  2.9805,  0.7438,  0.6412, -0.1275,
          0.4197,  0.4124],
        [ 0.3022, -0.8782, -1.1405,  0.6778,  0.0910,  0.8221,  0.5826, -1.1443,
          0.1133, -1.9675],
        [-0.0872,  0.2376,  0.2568, -0.0889,  0.3757,  1.1661, -1.2175, -0.5541,
         -1.0031,  0.6302],
        [-0.4699,  0.5458,  0.6909,  0.0645,  0.1643, -0.0718,  0.8474, -1.4140,
          1.7196, -0.4215],
        [-1.2677,  0.5189,  1.0236, -0.6413, -0.9892, -1.3942, -1.4767,  1.7769,
          0.7540, -0.5320],
        [-0.0408,  1.1714, -0.0429,  0.8475, -0.6490,  0.2885, -1.2409, -0.9790,
          0.1976,  0.8879]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



In [13]:
# 4. Создайте случайный IntTensor размера 10
random_int_tensor = torch.randint(0, 10, (10,))
print_tens_info(random_int_tensor)

X :
tensor([6, 5, 1, 3, 3, 2, 8, 8, 0, 9])

X количество измерений:
1

X размеры :  torch.Size([10])
X тип : torch.LongTensor



In [15]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
elementwise_multiplied_tensor = reshaped_float_tensor * random_int_tensor
print_tens_info(elementwise_multiplied_tensor)

X :
tensor([[-12.3201,   3.4640,  -1.1283,   0.2177,   8.9414,   1.4875,   5.1299,
          -1.0202,   0.0000,   3.7112],
        [  1.8135,  -4.3910,  -1.1405,   2.0334,   0.2729,   1.6443,   4.6604,
          -9.1540,   0.0000, -17.7076],
        [ -0.5233,   1.1879,   0.2568,  -0.2667,   1.1272,   2.3323,  -9.7396,
          -4.4327,  -0.0000,   5.6720],
        [ -2.8191,   2.7292,   0.6909,   0.1936,   0.4928,  -0.1435,   6.7793,
         -11.3117,   0.0000,  -3.7933],
        [ -7.6060,   2.5947,   1.0236,  -1.9240,  -2.9677,  -2.7883, -11.8132,
          14.2154,   0.0000,  -4.7883],
        [ -0.2447,   5.8571,  -0.0429,   2.5426,  -1.9470,   0.5770,  -9.9270,
          -7.8319,   0.0000,   7.9909]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



In [16]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
matrix_multiplied_tensor = torch.matmul(reshaped_float_tensor, reshaped_float_tensor.T)
print_tens_info(matrix_multiplied_tensor)

X :
tensor([[16.1844,  0.7452,  1.1636,  2.2760, -3.3007, -0.9363],
        [ 0.7452,  8.8396, -1.0240,  1.7260, -5.4385, -1.5667],
        [ 1.1636, -1.0240,  4.8316, -1.9185, -1.7222,  2.7025],
        [ 2.2760,  1.7260, -1.9185,  6.8845, -0.7609,  0.8546],
        [-3.3007, -5.4385, -1.7222, -0.7609, 12.4471,  0.0813],
        [-0.9363, -1.5667,  2.7025,  0.8546,  0.0813,  5.9240]])

X количество измерений:
2

X размеры :  torch.Size([6, 6])
X тип : torch.FloatTensor



In [17]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor(1.0, requires_grad=True)
z = torch.tensor(0.5, requires_grad=True)
t = torch.tensor(2.0, requires_grad=True)

y = x**3 + z - 75*t
y.backward()
print("dy/dx:", x.grad.item())
print("dy/dz:", z.grad.item())
print("dy/dt:", t.grad.item())

dy/dx: 3.0
dy/dz: 1.0
dy/dt: -75.0


In [18]:
# 8. Создайте единичный тензор размера 5x6
identity_tensor = torch.eye(5, 6)
print_tens_info(identity_tensor)

X :
tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

X количество измерений:
2

X размеры :  torch.Size([5, 6])
X тип : torch.FloatTensor



In [21]:
# 9. Переведите его в формат numpy
numpy_identity_tensor = identity_tensor.numpy()
numpy_identity_tensor

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)

In [22]:
# 10. Оптимизация с помощью функции y = x**w1 - 2 * x**2 + 5
x_opt = torch.tensor(1.0, requires_grad=True)
w1 = torch.tensor(2.0, requires_grad=True)

y_opt = x_opt**w1 - 2 * x_opt**2 + 5
y_opt.backward()

print("dy/dx_opt:", x_opt.grad.item())
print("dy/dw1:", w1.grad.item())

dy/dx_opt: -2.0
dy/dw1: 0.0


## Обучение простой нейронной сети, которая решает задачу умножения на вектор из 10 чисел

In [177]:
import torch.nn as nn
import torch.optim as optim

In [193]:
# Обучающие данные
train_data = reshaped_float_tensor[:5]
train_labels = elementwise_multiplied_tensor[:5]

In [194]:
# Тестовые данные
test_data = reshaped_float_tensor[5:]
test_labels = elementwise_multiplied_tensor[5:]

In [195]:
# Создаем класс для простой линейной нейронной сети
class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.linear = nn.Linear(10, 10)

    def forward(self, x):
        return self.linear(x)

In [196]:
# Создаем экземпляр нейронной сети
model = SimpleNN()

In [197]:
# Определяем функцию потерь
criterion = nn.MSELoss()

In [198]:
# Определяем оптимизатор (SGD)
optimizer = optim.SGD(model.parameters(), lr=0.01)

In [199]:
# Цикл обучения
epochs = 3000
for epoch in range(epochs):
    # Обнуляем градиенты
    optimizer.zero_grad()

    # Прямой проход (получение предсказания модели)
    predictions = model(train_data)

    # Вычисление функции потерь
    loss = criterion(predictions, train_labels)

    # Обратное распространение ошибки (рассчет градиентов)
    loss.backward()

    # Обновление весов
    optimizer.step()

    # Выводим значение функции потерь каждые 100 эпох
    if epoch % 200 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

Epoch 0, Loss: 32.9001579284668
Epoch 200, Loss: 5.834619522094727
Epoch 400, Loss: 1.8222668170928955
Epoch 600, Loss: 0.7344302535057068
Epoch 800, Loss: 0.32941052317619324
Epoch 1000, Loss: 0.1552087962627411
Epoch 1200, Loss: 0.0750538632273674
Epoch 1400, Loss: 0.03686970844864845
Epoch 1600, Loss: 0.018308617174625397
Epoch 1800, Loss: 0.00916531402617693
Epoch 2000, Loss: 0.004617521073669195
Epoch 2200, Loss: 0.002338301157578826
Epoch 2400, Loss: 0.001189094502478838
Epoch 2600, Loss: 0.0006068135262466967
Epoch 2800, Loss: 0.0003105575160589069


In [200]:
# Тестирование на тестовых данных
with torch.no_grad():
    # Получаем предсказания модели на тестовых данных
    test_predictions = model(test_data)

In [201]:
# Выводим результат предсказания на тестовых данных
print(test_predictions)

tensor([[-0.2267,  1.6594,  1.6066, -0.4661, -0.4011,  1.6158, -6.3304, -5.9989,
          0.3961,  3.8764]])


In [202]:
# Выводим реальные данные
print (test_labels)

tensor([[-0.2447,  5.8571, -0.0429,  2.5426, -1.9470,  0.5770, -9.9270, -7.8319,
          0.0000,  7.9909]])
